#!/bin/bash

############Do Not edit this file###############
##########Line numbers used#############
IP=`grep -v "#" /etc/fstab | grep nfs |awk {'print $1'} | cut -d: -f1 | exec sed 's/#//g'`
NFS1=172.31.25.48
NFS2=172.31.25.3

 ping -q -c5 172.31.25.48 > /dev/null
  if [ $? -eq 0 ]
    then
    echo "Host is available"  
    if [ "$IP" = "$NFS2" ]
      then
       umount -f -l /mnt/data/stag
       sed -i '/172.31.25.48/s/^#*//g' /etc/fstab
       sed -i '/172.31.25.3/s/^/#/g' /etc/fstab
       mount -a
       sed -i '22i umount -f -l /mnt/data/stag' /scripts/nfs_ha.sh
    fi  
else
umount -f -l /mnt/data/stag
    sed -i '/172.31.25.3/s/^#//g' /etc/fstab
    sed -i '/172.31.25.48/s/^/#/g' /etc/fstab
    mount -a
    sed -i '20,23{/umount/d}' nfs_ha.sh
fi

